apiVersion: postgres-operator.crunchydata.com/v1beta1
kind: PostgresCluster
metadata:
  name: harbor
spec:
  image: registry.developers.crunchydata.com/crunchydata/crunchy-postgres:ubi8-14.4-0
  postgresVersion: 14
  instances:
    - name: harbor-ha-instance
      replicas: 2
      dataVolumeClaimSpec:
        storageClassName: nfs-sc
        accessModes:
          - "ReadWriteOnce"
        resources:
          requests:
            storage: 15Gi
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/instance-set: harbor_ha_instance
  backups:
    pgbackrest:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbackrest:ubi8-2.38-2
      repos:
        - name: repo1
          volume:
            volumeClaimSpec:
              storageClassName: nfs-sc
              accessModes:
                - "ReadWriteOnce"
              resources:
                requests:
                  storage: 15Gi
  proxy:
    pgBouncer:
      image: registry.developers.crunchydata.com/crunchydata/crunchy-pgbouncer:ubi8-1.16-4
      replicas: 2
      service:
        type: NodePort
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 1
              podAffinityTerm:
                topologyKey: kubernetes.io/hostname
                labelSelector:
                  matchLabels:
                    postgres-operator.crunchydata.com/cluster: harbor
                    postgres-operator.crunchydata.com/role: pgbouncer
  users:
    - name: harbor
      databases:
        - harbor
  service:
    type: NodePort