apiVersion: triggers.tekton.dev/v1beta1
kind: EventListener
metadata:
  name: trigger-demo-pipeline-eventlistener
spec:
  resources:
    kubernetesResource:
      serviceType: NodePort
  serviceAccountName: tekton-triggers-gitlab-sa
  triggers:
    - bindings:
        - ref: tr-demo-pipeline-binding
      template:
        ref: tr-demo-pipeline-template
---
apiVersion: v1
kind: Secret
metadata:
  name: gitlab-secret
type: Opaque
stringData:
  secretToken: ""
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-triggers-gitlab-sa
secrets:
- name: gitlab-secret
- name: gitlab-auth
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-triggers-gitlab-demo
rules:
  # Permissions for every EventListener deployment to function
  - apiGroups: ["triggers.tekton.dev"]
    resources: ["eventlisteners", "interceptors", "triggerbindings", "triggertemplates","clustertriggerbindings", "clusterinterceptors","triggers"]
    verbs: ["get","list","watch"]
  - apiGroups: [""]
    # secrets are only needed for Github/Gitlab interceptors, serviceaccounts only for per trigger authorization
    resources: ["configmaps", "secrets", "serviceaccounts"]
    verbs: ["get", "list", "watch"]
  # Permissions to create resources in associated TriggerTemplates
  - apiGroups: ["tekton.dev"]
    resources: ["pipelineruns", "pipelineresources", "taskruns"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: tekton-triggers-gitlab-demo-binding
subjects:
  - kind: ServiceAccount
    name: tekton-triggers-gitlab-sa
    namespace: demo
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: tekton-triggers-gitlab-demo
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: tr-demo-pipeline-binding
spec:
  params:
    - name: git-rev
      value: $(body.ref)
    - name: git-repourl
      value: $(body.repository.homepage)
    - name: project-name
      value: $(body.repository.name)
    - name: git-checkout-sha
      value: $(body.checkout_sha)
---
apiVersion: triggers.tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: tr-demo-pipeline-template
spec:
  params:
    - name: git-rev
      description: The git revision
      default: master
    - name: git-repourl
      description: The git repository url
    - name: project-name
      description: The git repository name
    - name: git-checkout-sha
      description: The git checkout sha
  resourcetemplates:
    - apiVersion: tekton.dev/v1alpha1
      kind: PipelineRun
      metadata:
        name: demo-pipeline-run-$(uid)
      spec:
        params:
        - name: revision
          value: $(tt.params.git-rev)
        - name: ssh-host
          value: xxx
        - name: git-repourl
          value: $(tt.params.git-repourl)
        - name: project-name
          value: $(tt.params.project-name)
        - name: git-checkout-sha
          value: $(tt.params.git-checkout-sha)
        - name: docker-user
          value: xxx
        - name: docker-pass
          value: xxx
        pipelineRef:
          name: demo-pipeline
        workspaces:
        - name: ssh-credentials
          secret:
            secretName: demo-secret