---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: tekton-pipelinerun-creater
  labels:
    app: tekton-pipelinerun-creater
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-pipelinerun-creater
  labels:
    app: tekton-pipelinerun-creater
rules:
  - apiGroups:
      - tekton.dev
    resources:
      - pipelineruns
    verbs:
      - create
      - get
      - watch
      - list
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tekton-pipelinerun-creater
  labels:
    app: tekton-pipelinerun-creater
roleRef:
  kind: Role
  name: tekton-pipelinerun-creater
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: tekton-pipelinerun-creater
---